# permissions for end users to view storageprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageprofile-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageprofiles/status
  verbs:
  - get
