# permissions for end users to edit storageprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageprofile-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageprofiles/status
  verbs:
  - get
