# permissions for end users to view storagerequestss.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagerequest-viewer-role
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storagerequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storagerequests/status
    verbs:
      - get
