# permissions for end users to edit storagerequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagerequest-editor-role
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storagerequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storagerequests/status
    verbs:
      - get
