kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onboarding-validation-keys-generator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageclusters
  verbs:
    - get
    - list
